### ISSUE TITLE
laravel-scout-typesense-driver  Get config error

### ISSUE THREAD

**Issue by Numer0x** [typesense/laravel-scout-typesense-engine#93]
## Description

I'm trying to use the Scout extension in my Laravel 11 project with Typesense as the search engine, but I couldn't retrieve or access the configured settings.Perhaps this is because the validateConfigArray() function in Configuration.php directly retrieves node configuration instead of retrieving it through the correct path, resulting in Scout configuration being ignored since it actually resides under client-settings.

## Steps to reproduce

![image](https://github.com/user-attachments/assets/20f2e037-ec79-4784-9772-8fa8d8dedecc)

![image](https://github.com/user-attachments/assets/ef08b7cc-ccd9-49cb-ae43-ada81f22788e)

![image](https://github.com/user-attachments/assets/041c65b1-2a97-49a6-9627-aebe4b2947da)

[2024-09-26 04:44:02] local.ERROR: `nodes` is not defined. {"exception":"[object] (Typesense\\Exceptions\\ConfigError(code: 0): `nodes` is not defined. at /var/www/ResourceManager/vendor/typesense/typesense-php/src/Lib/Configuration.php:121)
[stacktrace]
#0 /var/www/ResourceManager/vendor/typesense/typesense-php/src/Lib/Configuration.php(78): Typesense\\Lib\\Configuration->validateConfigArray()
#1 /var/www/ResourceManager/vendor/typesense/typesense-php/src/Client.php(86): Typesense\\Lib\\Configuration->__construct()
#2 /var/www/ResourceManager/vendor/typesense/laravel-scout-typesense-driver/src/TypesenseServiceProvider.php(29): Typesense\\Client->__construct()

## Expected Behavior

![image](https://github.com/user-attachments/assets/45215e11-af0f-4d20-8bdb-cbf72c24bc44)

When the configuration file is set up this way, it can be used normally

## Metadata

**Typesense Version**: 27.0

**OS**:macos 15

**Comment by Numer0x** [comment]
Is there something wrong with my usage or configuration?

**Comment by WanderingDaniel** [comment]
Just to add - 

Experiencing this with Laravel 10 the latest typesense driver also. Same as above, if I do it sans the client path it works, but with the client path it provides incorrect config.

**Comment by captjay98** [comment]
Currently facing the same problem. Did you find your way around?

**Comment by WanderingDaniel** [comment]
> Currently facing the same problem. Did you find your way around?

For now I've just got my config file like

  ```
  'typesense' => [
            'api_key' => env('TYPESENSE_API_KEY'),
            'nodes' => [
                [
                    'host' => env('TYPESENSE_HOST', 'localhost'),
                    'port' => env('TYPESENSE_PORT', '8108'),
                    'protocol' => env('TYPESENSE_PROTOCOL', 'http'),
                ],
            ],
            'nearest_node' => [
                'host' => env('TYPESENSE_HOST', 'localhost'),
                'port' => env('TYPESENSE_PORT', '8108'),
                'path' => env('TYPESENSE_PATH', ''),
                'protocol' => env('TYPESENSE_PROTOCOL', 'http'),
            ],
            'connection_timeout_seconds' => env('TYPESENSE_CONNECTION_TIMEOUT_SECONDS', 2),
            'healthcheck_interval_seconds' => env('TYPESENSE_HEALTHCHECK_INTERVAL_SECONDS', 30),
            'num_retries' => env('TYPESENSE_NUM_RETRIES', 3),
            'retry_interval_seconds' => env('TYPESENSE_RETRY_INTERVAL_SECONDS', 1),
    ],
```

(Noting sans the client-settings), and this is working for me.
